/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("com.example.common.kotlin-base")
    id("com.example.testing.test-base")
}
