/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("com.example.development.springboot-app-conventions")

    id("com.example.testing.test-base")
    id("com.example.testing.springboot-test-dependencies")

    id("com.example.standalone.standalone-dependencies")
    id("com.example.standalone.standalone-plugins")
}

dependencies {
    // https://tomgregory.com/how-to-use-gradle-api-vs-implementation-dependencies-with-the-java-library-plugin/
    api(project(":domain"))

    // Just an example to add very specific dependency
    implementation("org.apache.commons:commons-text")
}
